apiVersion: v1
kind: Service

metadata:
  name: atc-todo-service
  namespace: atc
spec:
  selector:
    app: atc-todo-app

  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

  type: NodePort
